### ISSUE TITLE
Latest Version of Mod doesn't Work

### ISSUE THREAD

**Issue by Shadow212121** [LordDeatHunter/Croptosis#10]
When i load the game with the latest version of the mod in my mods folder the game does not detect it at all. I tried with and without my other mods installed with the same result. Not sure why but Forge doesn't even detect its there.

**Comment by Shadow212121** [comment]
NVM found out from comments on the curseforge page this is a fabric mod. May want to put a disclaimer there for people so they know.

**Comment by LordDeatHunter** [comment]
I always do.
CurseForge has an option to show only forge mods, however, it's gotten a bit more convoluted lately.
![image](https://user-images.githubusercontent.com/26803198/146271233-d064e3b1-8e40-478f-ba31-d1208dd7f4ef.png)
