### ISSUE TITLE
Sandwichable and ValleyCraft crops not compatible.

### ISSUE THREAD

**Issue by nephatrine** [LordDeatHunter/Croptosis#12]
The crops from these two mods are not able to be planted on croptosis fertilized soil. I am using `wraith-croptosis-1.4.2` in 1.18.1.

**Comment by LordDeatHunter** [comment]
Cannot replicate with latest versions.
![image](https://user-images.githubusercontent.com/26803198/168488846-240cb3e3-5096-4fab-aea6-1b4cb464f01e.png)

**Comment by LordDeatHunter** [comment]
Closing the issue as I cannot reproduce, if you run into it again, feel free to re-open with more info.
