### ISSUE TITLE
Plants disappear on fertilized soil

### ISSUE THREAD

**Issue by Polarite** [LordDeatHunter/Croptosis#13]
for some reason after I plant anything on fertilized soil it disappears instantly
fabric 1.18.2

**Comment by LordDeatHunter** [comment]
Modded or vanilla crops? Is this on singleplayer or multiplayer? If multiplayer, is it installed on both server & client?

**Comment by LordDeatHunter** [comment]
Closing the issue as I cannot reproduce, if you run into it again, feel free to re-open with more info.
