### ISSUE TITLE
Game crashes after placing Fertilized Sand

### ISSUE THREAD

**Issue by elidhan** [LordDeatHunter/Croptosis#8]
Error message:

The game crashed whilst exception ticking world
Error: java.lang.IllegalArgumentException: Cannot get property class_2758{name=max_height, clazz=class java.lang.Integer, values=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]} as it does not exist in Block{croptosis:fertilized_sand}
Exit Code: -1

Game now crashes instantly when loading world

**Comment by LordDeatHunter** [comment]
Can you send the entire crash file?
Also, for future reference, running the game with https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes gives clearer error messages.

**Comment by elidhan** [comment]
Download: [crash-2021-11-09_23.33.06-server.txt](https://github.com/LordDeatHunter/Croptosis/files/7533660/crash-2021-11-09_23.33.06-server.txt)

Full report:

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 09/11/21 23:33
Description: Exception ticking world

java.lang.IllegalArgumentException: Cannot get property class_2758{name=max_height, clazz=class java.lang.Integer, values=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]} as it does not exist in Block{croptosis:fertilized_sand}
	at net.minecraft.class_2688.method_11654(class_2688.java:95)
	at wraith.croptosis.block.FertilizedSandBlock.method_9514(FertilizedSandBlock.java:36)
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:878)
	at net.minecraft.class_3218.redirect$bfl000$redirectBlockStateTick(class_3218.java:5583)
	at net.minecraft.class_3218.method_18203(class_3218.java:522)
	at net.minecraft.class_3215.method_20801(class_3215.java:390)
	at net.minecraft.class_3215$$Lambda$6530/686117864.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at net.minecraft.class_3215.method_14161(class_3215.java:368)
	at net.minecraft.class_3215.method_12127(class_3215.java:337)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$5933/1640368173.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_2688.method_11654(class_2688.java:95)
	at wraith.croptosis.block.FertilizedSandBlock.method_9514(FertilizedSandBlock.java:36)
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:878)
	at net.minecraft.class_3218.redirect$bfl000$redirectBlockStateTick(class_3218.java:5583)
	at net.minecraft.class_3218.method_18203(class_3218.java:522)
	at net.minecraft.class_3215.method_20801(class_3215.java:390)
	at net.minecraft.class_3215$$Lambda$6530/686117864.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at net.minecraft.class_3215.method_14161(class_3215.java:368)
	at net.minecraft.class_3215.method_12127(class_3215.java:337)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)

-- Affected level --
Details:
	All players: 1 total; [class_3222['PR_Eli'/116, l='ServerLevel[Frontier [1.16.5 Fabric]]', x=112.38, y=63.00, z=-287.95]]
	Chunk stats: ServerChunkCache: 2482
	Level dimension: minecraft:overworld
	Level spawn location: World: (48,69,-63), Chunk: (at 0,4,1 in 3,-4; contains blocks 48,0,-64 to 63,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 179923 game time, 205888 day time
	Level name: Frontier [1.16.5 Fabric]
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 55777 (now: false), thunder time: 36141 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$5933/1640368173.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 854949752 bytes (815 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		antiqueatlas: Antique Atlas 6.1.0-fabric-mc1.16.5
		atmosfera: Atmosfera 1.4.2+mc1.16.5
		autoconfig1u: Auto Config v1 Updated 3.3.1
		battletowers: Battle Towers 3.3.4-1.16.4
		bclib: BCLib 0.1.45
		betterdungeons: YUNG's Better Dungeons 1.16.5-1.0.1
		betterend: Better End 0.9.8.5-pre
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.2
		betternether: Better Nether 5.0.7
		betterstrongholds: YUNG's Better Strongholds 1.16.5-1.1.1
		cardinal-components-base: Cardinal Components API (base) 2.8.2
		cardinal-components-chunk: Cardinal Components API (chunks) 2.8.1
		cardinal-components-entity: Cardinal Components API (entities) 2.8.2
		carrier: Carrier 1.7.6
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.26
		collective-fabric: Collective (Fabric) 1.61
		croptosis: Croptosis 1.1.0
		daylight_mobs_reborn: Daylight Mobs Reborn 1.2.1
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		eldritch_mobs: Eldritch Mobs 1.8.0
		fabric: Fabric API 0.41.3+1.16
		fabric-api-base: Fabric API Base 0.3.0+f74f7c7d7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+f74f7c7d7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.12+c16be54b7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+f74f7c7d7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.4+f74f7c7d7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.7+c16be54b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.3+77df1b337d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.4+35ff49a47d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+f74f7c7d7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.0+ede6dcf77d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+f74f7c7d7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.5+kotlin.1.5.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+f74f7c7d7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.4+f74f7c7d7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+f74f7c7d7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.5+9385714e7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+f74f7c7d7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+f74f7c7d7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4579bd497d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+f74f7c7d7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+f74f7c7d7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+ca0ef93d7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+f74f7c7d7d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.4.1+c16be54b7d
		fabricloader: Fabric Loader 0.12.4
		fallingtree: FallingTree 2.11.5
		fiber: fiber 0.23.0-2
		fixedanvilrepaircost-fabric: Fixed Anvil Repair Cost (Fabric) 1.6
		flesh2leather: Flesh2Leather 1.0.2
		gateofbabylon: Gate Of Babylon 1.4.4-1.16.5
		graveyard: The Graveyard 1.0
		harvest_scythes: Harvest Scythes 2.0.4
		hydrogen: Hydrogen 0.2
		inmis: Inmis 2.2.1-1.16.5
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		libgui: LibGui 3.3.5+1.16.5
		libstructure: LibStructure 1.5
		lithium: Lithium 0.6.6
		mambience: MAmbience 3.1.1+1.16.5
		minecraft: Minecraft 1.16.5
		musketmod: Musket Mod 1.2.2
		omega-config: OmegaConfig 1.0.4
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
		phosphor: Phosphor 0.7.2+build.12
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		repurposed_structures: Repurposed Structures 1.16.5-1.11.6-fabric
		roughlyenoughitems: Roughly Enough Items 5.12.248
		roughlyenoughitems-api: REI (API) 5.12.248
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.12.248
		roughlyenoughitems-runtime: REI (Runtime) 5.12.248
		rpgstats: RPGStats 4.0.5+1.16.5
		sodium: Sodium 0.2.0+build.4
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		structure-helpers: Structure Helpers 3.0.0
		voyager: Voyager 1.0.0
		william-wythers-overhauled-overworld: William Wythers Overhauled Overworld 1.0
		yungsapi: YUNG's API 1.16.5-Fabric-9
	Player Count: 1 / 8; [class_3222['PR_Eli'/116, l='ServerLevel[Frontier [1.16.5 Fabric]]', x=112.38, y=63.00, z=-287.95]]
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by LordDeatHunter** [comment]
Pretty sure this is fixed in later releases. 1.16.5 is no longer supported, and I'm unsure if I'll come back to past versions for an update.
